// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duwutbuyezcfqjfopbva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1d3V0YnV5ZXpjZnFqZm9wYnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTE1NjMsImV4cCI6MjA2NTA2NzU2M30.s8LhJRXJ4QAFwjntnwrNbyBCGdO40pw8bIk2v7SRZnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);